# Generated by Django 4.0.4 on 2022-06-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email_address', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('FEEDBACK', 'Feedback'), ('OTHER', 'other')], default='SUGGESTION', max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
