# Generated by Django 4.0.4 on 2022-06-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='subject_type',
            field=models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], default='SUGGESTION', max_length=10),
        ),
    ]
